-- liquibase formatted sql

-- changeset enes:transportation-table
CREATE TABLE IF NOT EXISTS transportation
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_id           BIGINT    NOT NULL,
    destination_id      BIGINT    NOT NULL,
    transportation_type SMALLINT  NOT NULL,
    operating_days      INTEGER[]          DEFAULT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP          DEFAULT NULL,
    CONSTRAINT fk_origin_id FOREIGN KEY (origin_id) REFERENCES location (id),
    CONSTRAINT fk_destination_id FOREIGN KEY (destination_id) REFERENCES location (id)
);

-- changeset enes:transportation-updated-at-trigger
CREATE OR REPLACE TRIGGER transportation_trigger_set_updated_at
    BEFORE UPDATE
    ON transportation
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
