-- liquibase formatted sql

-- changeset enes:transportation-table
CREATE TABLE IF NOT EXISTS transportation
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin              VARCHAR(255) NOT NULL,
    destination         VARCHAR(255) NOT NULL,
    transportation_type SMALLINT NOT NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP             DEFAULT NULL
);

-- changeset enes:transportation-updated-at-trigger
CREATE OR REPLACE TRIGGER transportation_trigger_set_updated_at
    BEFORE UPDATE
    ON transportation
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
