-- liquibase formatted sql

-- changeset enes:transportation-table
CREATE TABLE IF NOT EXISTS transportation
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin              BIGINT    NOT NULL,
    destination         BIGINT    NOT NULL,
    transportation_type SMALLINT  NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP          DEFAULT NULL,
    CONSTRAINT fk_origin FOREIGN KEY (origin) REFERENCES location (id),
    CONSTRAINT fk_destination FOREIGN KEY (destination) REFERENCES location (id)
);

-- changeset enes:transportation-updated-at-trigger
CREATE OR REPLACE TRIGGER transportation_trigger_set_updated_at
    BEFORE UPDATE
    ON transportation
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
