-- liquibase formatted sql

-- changeset enes:location-table
CREATE TABLE IF NOT EXISTS location
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    country       VARCHAR(250) NOT NULL,
    city          VARCHAR(250) NOT NULL,
    location_code VARCHAR(10)  NOT NULL UNIQUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP             DEFAULT NULL
);

-- changeset enes:location-country-idx
CREATE INDEX idx_country
    ON location (country);

-- changeset enes:location-updated-at-trigger
CREATE OR REPLACE TRIGGER location_trigger_set_updated_at
    BEFORE UPDATE
    ON location
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
